# Chapter 7: Numbers

## TL;DR

There are three numeric types that are part of core Python:
- *integers* (with booleans as a special sub-type)
- *floats* (that are inherently imprecise)
- *complex* numbers

Furthermore, the Standard Library adds two more (precise) types that can be used as substitutes for *floats*:
- [Decimals](https://docs.python.org/3/library/decimal.html#decimal.Decimal)
- [Fractions](https://docs.python.org/3/library/fractions.html#fractions.Fraction)

An important fact that holds for all the data types presented in this notebook is that theirs objects are **immutable**. That implies that any operation or method applied to a numeric value always returns a new object (i.e., different memory location), potentially with the same value.

## Integers

The simplest type of a number is an integer. They behave just like integers in ordinary math (i.e., the set $\mathbb{Z}$) and support Python operators in the way we saw in the section on (arithmetic) operators in chapter 1.

An integer is its own object with a memory location and type.

In [1]:
a = 789

In [2]:
id(a)

140652016286352

In [3]:
type(a)

int

In [4]:
a

789

A nice feature is the usage of underscores "\_" as (thousands) seperators in numeric literals. For example, `1_000_000` evaluates to just `1000000` in memory.

In [5]:
1_000_000

1000000

Whereas mathematicians argue what the term $0^0$ means (see [Wikipedia](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero)), programmers are more pragmatic about this and just define $0^0 = 1$.

In [6]:
0 ** 0

1

### Binary Representations

As computers can only store collections of $0$s and $1$s, also integers are nothing but that under the hood. Consequently, computer scientists and engineers developed conventions as to how the $1$s and $0$s are composed together to mean numeric values other than $0$s and $1$s.

One such convention is the **binary representation** of **non-negative integers**. For the following example, consider the integers from $0$ to $255$ that are encoded into $0$s and $1$s with the help of this table:

|Bit $i$|  7  |  6  |  5  |  4  |  3  |  2  |  1  |  0  |
|-------|-----|-----|-----|-----|-----|-----|-----|-----|
| Digit |$2^7$|$2^6$|$2^5$|$2^4$|$2^3$|$2^2$|$2^1$|$2^0$|
|  $=$  |$128$| $64$| $32$| $16$| $8$ | $4$ | $2$ | $1$ |

A number consists of exactly eight $0$s and $1$s that are commonly read from right to left and referred to as the **bits** of a number (we start counting at $0$ again). Each bit represents a distinct numeric value or *digit* as indicated in the table.

In order to encode an integer of $3$, for example, we need to find a combination of $0$s and $1$s such that the sum of digits marked with a $1$ is equal to the number we want to encode. In the example, we set all bits to $0$ except for the first ($i=0$) and second ($i=1$) because $1 + 2 = 3$. So the binary representation of $3$ becomes $00~00~00~11$. To be even more precise, the $3$ can be seen as a linear combination of the digits where the coefficients are one of two values: $3 = 0*128 + 0*64 + 0*32 + 0*16 + 0*8 + 0*4 + 1*2 + 1*1$. It is guaranteed that there is exactly one such combination for each number between $0$ and $255$.

As each digit can only be one of two values, we say that this representation has a base of $2$. Often times, we indicate the base with a subscript to avoid any confusion. For example, we could write $3_{10} = 00000011_2$ or even shorter $3_{10} = 11_2$ if we omit leading $0$s. A subscript of $10$ implies a decimal number as we know it from grade school.

In Python, we can use the built-in function [bin()](https://docs.python.org/3/library/functions.html#bin) to obtain the binary representation of an integer. It returns a string starting with "0b" indicating the binary format and as many $0$s and $1$s as are necessary to encode the integer omitting leading $0$s.

So the binary representation of $3$ in Python is as follows.

In [7]:
bin(3)

'0b11'

The output of [bin()](https://docs.python.org/3/library/functions.html#bin) is itself a valid Python expression meaning that we can just enter it back into a code cell or use it as the argument to the [int()](https://docs.python.org/3/library/functions.html#int) built-in function (together with `base=2`) and obtain the original $3$ back.

In [8]:
"0b11"

'0b11'

In [9]:
int("0b11", base=2)

3

Another example is the integer $177$ which can be viewed as the sum of $128 + 32 + 16 + 1$, and consequently, as a sequence of bits $10~11~00~01$. So, in our new notation $177_{10} = 10110001_2$.

In [10]:
bin(177)

'0b10110001'

$0$ and $255$ are just the cases where we set the bits to either only $0$s or $1$s.

In [11]:
bin(0)

'0b0'

In [12]:
bin(1)

'0b1'

In [13]:
bin(2)

'0b10'

In [14]:
bin(255)

'0b11111111'

Groups of eight bits are also referred to as a **byte**. As a byte can only store non-negative integers up to $255$, the table above is extended conceptually with greater digits to the left to express integers beyond $255$. The memory management needed to implement these automatic extensions is built into Python and we do not need to worry about this.

For example, the $789$ from above is encoded with $10$ bits and $789_{10} = 1100010101_2$.

In [15]:
bin(a)

'0b1100010101'

Just to contrast this new encoding in bits with the familiar decimal system, we view an equivalent table with powers of $10$ as the digits:

|Decimal|   3  |   2  |   1  |   0  |
|-------|------|------|------|------|
| Digit |$10^3$|$10^2$|$10^1$|$10^0$|
|  $=$  |$1000$| $100$| $10$ |  $1$ |

Now, an integer can be viewed as a linear combination of the digits again where the coefficents are one of ten values. For example, the number $123$ can be expressed as $0*1000 + 1*100 + 2*10 + 3*1$. So the binary representation follows the same logic as the decimal system taught in grade school.

#### Hexadecimal Representations

While in the binary and decimal systems there are two and ten distinct coefficients per digit, another convenient representation uses a base of $16$ and is called **hexadecimal**. It is convenient as one digit stores the same amount of information as four bits and the bits representation quickly becomes unreadable for larger values. As humans are used to counting in the decimal system (because we have 10 fingers), the letters "a" through "f" are used as digits "10" through "15". The following table summarizes the relationship between the systems:

|Decimal|Hexadecimal|Binary|$~~~~~~$|Decimal|Hexadecimal|Binary|$~~~~~~$|Decimal|Hexadecimal|Binary|$~~~~~~$|...|
|-------|-----------|------|--------|-------|-----------|------|--------|-------|-----------|------|--------|---|
|   0   |     0     | 0000 |$~~~~~~$|  16   |    10     | 10000|$~~~~~~$|  32   |    20     |100000|$~~~~~~$|...|
|   1   |     1     | 0001 |$~~~~~~$|  17   |    11     | 10001|$~~~~~~$|  33   |    21     |100001|$~~~~~~$|...|
|   2   |     2     | 0010 |$~~~~~~$|  18   |    12     | 10010|$~~~~~~$|  34   |    22     |100010|$~~~~~~$|...|
|   3   |     3     | 0011 |$~~~~~~$|  19   |    13     | 10011|$~~~~~~$|  35   |    23     |100011|$~~~~~~$|...|
|   4   |     4     | 0100 |$~~~~~~$|  20   |    14     | 10100|$~~~~~~$|  36   |    24     |100100|$~~~~~~$|...|
|   5   |     5     | 0101 |$~~~~~~$|  21   |    15     | 10101|$~~~~~~$|  37   |    25     |100101|$~~~~~~$|...|
|   6   |     6     | 0110 |$~~~~~~$|  22   |    16     | 10110|$~~~~~~$|  38   |    26     |100110|$~~~~~~$|...|
|   7   |     7     | 0111 |$~~~~~~$|  23   |    17     | 10111|$~~~~~~$|  39   |    27     |100111|$~~~~~~$|...|
|   8   |     8     | 1000 |$~~~~~~$|  24   |    18     | 11000|$~~~~~~$|  40   |    28     |101000|$~~~~~~$|...|
|   9   |     9     | 1001 |$~~~~~~$|  25   |    19     | 11001|$~~~~~~$|  41   |    29     |101001|$~~~~~~$|...|
|  10   |     a     | 1010 |$~~~~~~$|  26   |    1a     | 11010|$~~~~~~$|  42   |    2a     |101010|$~~~~~~$|...|
|  11   |     b     | 1011 |$~~~~~~$|  27   |    1b     | 11011|$~~~~~~$|  43   |    2b     |101011|$~~~~~~$|...|
|  12   |     c     | 1100 |$~~~~~~$|  28   |    1c     | 11100|$~~~~~~$|  44   |    2c     |101100|$~~~~~~$|...|
|  13   |     d     | 1101 |$~~~~~~$|  29   |    1d     | 11101|$~~~~~~$|  45   |    2d     |101101|$~~~~~~$|...|
|  14   |     e     | 1110 |$~~~~~~$|  30   |    1e     | 11110|$~~~~~~$|  46   |    2e     |101110|$~~~~~~$|...|
|  15   |     f     | 1111 |$~~~~~~$|  31   |    1f     | 11111|$~~~~~~$|  47   |    2f     |101111|$~~~~~~$|...|

To add to the above subscript convention, we pick three random entries from the table:

$11_{10} = \text{b}_{16} = 1011_2$

$25_{10} = 19_{16} = 11001_2$

$46_{10} = 2\text{e}_{16} = 101110_2$

The built-in function [hex()](https://docs.python.org/3/library/functions.html#hex) transforms an integer into its hexadecimal representation and returns a string starting with "0x". The length depends on how many groups of four bits are implied by the corresponding binary representation. As before, the output is itself a valid Python expression.

In [16]:
hex(0)

'0x0'

In [17]:
hex(1)

'0x1'

Whereas `bin(3)` would already require two digits, one is enough for `hex(3)`.

In [18]:
hex(3)

'0x3'

For $10$ through $15$ we see the letter digits for the first time.

In [19]:
hex(10)

'0xa'

In [20]:
hex(15)

'0xf'

The binary representation of $177_{10}$, `"0b10110001"`, can be read as two groups of four bits $1011$ and $0001$ that are encoded as $\text{b}$ and $1$ in accordance with the first three columns of the table above.

In [21]:
bin(177)

'0b10110001'

In [22]:
hex(177)

'0xb1'

Using the [int()](https://docs.python.org/3/library/functions.html#int) built-in function with `base=16`, we obtain the original integer back.

In [23]:
int("0xb1", base=16)

177

Hexadecimal values between $00$ and $\text{ff}$ (i.e., $0_{10}$ and $255_{10}$) are commonly used to describe colors, for example, in web development but also in graphics editors. See this [link](https://www.w3schools.com/colors/colors_hexadecimal.asp) for some more background.

In [24]:
hex(255)

'0xff'

Just like the binary representations, the hexadecimals extend to the left for larger values like `a = 789`.

In [25]:
hex(a)

'0x315'

We also mention that there is a built-in function [oct()](https://docs.python.org/3/library/functions.html#oct) that returns an **octal** representation of an integer. This works the same way as the hexadecimal representation where we just use eight distinct digits which is equivalent to viewing the binary representation in groups of three bits.

#### Negative Values

While there are various ways of how to model negative integers with just $0$s and $1$s (e.g., use a dedicated bit to indicate if a number is positive or negative), Python does that for us under the hood and the binary and hexadecimal representations of negative integers just start with a minus sign "-".

In [26]:
bin(-3)

'-0b11'

In [27]:
hex(-3)

'-0x3'

In [28]:
bin(-255)

'-0b11111111'

In [29]:
hex(-255)

'-0xff'

### Booleans

Whereas the boolean values `True` and `False` are commonly not regarded as numeric values, they act like `1` and `0` in an arithmetic context and are thus implicitly casted as integers.

In [30]:
b = True

In [31]:
id(b)

10299104

In [32]:
type(b)

bool

In [33]:
b

True

In [34]:
c = False

In [35]:
id(c)

10296512

In [36]:
type(c)

bool

In [37]:
c

False

By including booleans within an arithmetic expression, they magically work as integers.

In [38]:
b + c

1

In [39]:
a + b

790

In [40]:
a * c

0

We can also explicitly cast the booleans with the built-in [int()](https://docs.python.org/3/library/functions.html#int) function.

In [41]:
int(True)

1

In [42]:
int(False)

0

The binary representations only need one bit of information.

In [43]:
bin(True)

'0b1'

In [44]:
bin(False)

'0b0'

The hexadecimal representations occupy four bits while only one bit is needed. This is because the "1" and "0" are just two of the sixteen possible digits.

In [45]:
hex(True)

'0x1'

In [46]:
hex(False)

'0x0'

**Reminder**: `None` is a special "maybe" or "undefined" value that is different from `False`. We can clearly see with the `TypeError` that it cannot be casted as a number.

In [47]:
int(None)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

## Floats

As we have seen above, some assumptions need to be made as to how the $0$s and $1$s in a computer's memory should be translated into common numeric values. This process becomes a lot more involved when we go beyond just integers and want to model real numbers $\mathbb{R}$ in the mathematical sense, i.e., numbers with significant digits to the right of the period like $1.23$.

The **[Institute of Electrical and Electronics Engineers](https://en.wikipedia.org/wiki/Institute_of_Electrical_and_Electronics_Engineers)** (IEEE, pronounced "eye-tripple-E") is one of the most important professional associations when it comes to standardizing all kinds of things regarding the implementation of soft- and hardware.

The **[IEEE 754](https://en.wikipedia.org/wiki/IEEE_754)** standard defines the so-called **floating-point arithmetic** that is commonly used today by all major and relevant programming languages and Python is no exception to that. The standard not only defines how the $0$s and $1$s should be organized in a computer program but also, for example, how values are to be rounded, what happens in exceptional cases like divisions by zero, or what is a zero value to begin with.

In Python, the simplest notation to create a `float` is to just define a number with a dot `.` included in it. As always, a `float` is an object on its own.

In [51]:
d = 1.23

In [52]:
id(d)

140652016297424

In [53]:
type(d)

float

In [54]:
d

1.23

In cases where the dot `.` is unnecessary from a mathematical point of view, we either still need to end the number with it or use the [float()](https://docs.python.org/3/library/functions.html#float) built-in function to cast the number explicitly as a float.

In [55]:
1.  # on the contrary, 1 creates an integer object

1.0

In [56]:
float(1)

1.0

Floats are implicitly created as a result of dividing an integer by another with the "normal" division operator `/`.

In [57]:
1 / 3

0.3333333333333333

In general, if we combine floats and integers in arithmetic operations, we always end up with floats.

In [58]:
1.0 + 2

3.0

In [59]:
21 * 2.0

42.0

### Scientific Notation

Floats can also be created with a **scientifc notation** of the form $1.23 * 10^0$. In Python, we use the symbol `e` to indicate powers of $10$.

In [60]:
1.23e0

1.23

Syntactically, `e` needs a float in its simple notation (like `d` above) to its left and an integer to its right, both without a space. Otherwise, we get a `SyntaxError`.

In [61]:
1.23 e0

SyntaxError: invalid syntax (<ipython-input-61-1b5daaac0077>, line 1)

In [62]:
1.23e 0

SyntaxError: invalid syntax (<ipython-input-62-a236c4a30231>, line 1)

In [63]:
1.23e0.0

SyntaxError: invalid syntax (<ipython-input-63-05b9072d76be>, line 1)

Note also that if we leave out the number to the left, Python raises a `NameError` as it actually tries to look up a variable `e1`.

In [64]:
e1

NameError: name 'e1' is not defined

So, in order to write $10^1$ in Python, we actually need to write $1*10^1$.

In [65]:
1e1

10.0

### Special Values

There are also three special values representing **"not a number"** (NaN or nan) and positive or negative **infinity** (inf) that can be created by passing in the corresponding abbreviation as a text string to the [float()](https://docs.python.org/3/library/functions.html#float) built-in function. These values could be used, for example, as the result of a mathematically undefined operation like division by zero or to model the value of a mathematical function as it goes to infinity.

In [66]:
float("NaN")  # also works as float("nan")

nan

In [67]:
float("+inf")  # also works as float("+infinity")

inf

In [68]:
float("inf")  # by omitting the plus sign, we mean positive infinity

inf

In [69]:
float("-inf")

-inf

It is to be noted that NaN values never compare equal to anything, not even to themselves. This happens in accordance with the IEEE 754 standard.

In [70]:
float("NaN") == float("NaN")

False

On the contrary, once a value reaches infinity, there is no such concept as difference any more and everything compares equal.

In [71]:
float("inf") == float("inf")

True

In [72]:
float("inf") + 42

inf

In [73]:
float("inf") + 42 == float("inf")

True

In [74]:
42 * float("inf")

inf

In [75]:
42 * float("inf") == float("inf")

True

In [76]:
float("inf") ** 42

inf

In [77]:
float("inf") ** 42 == float("inf")

True

In [78]:
-42 * float("-inf")

inf

In [79]:
-42 * float("-inf") == float("inf")

True

Another caveat is that adding infinites of different signs is an undefined operation in math and returns NaN.

In [80]:
float("inf") + float("-inf")

nan

In [81]:
float("inf") - float("inf")

nan

### Imprecision

Floats are inherently imprecise. In particular, if their exponents are too far apart, arithmetic operations with two floats will result in weird "rounding" errors. These "errors" are actually stictly deterministic and occur as a consequence of the IEEE 754 standard.

For example, let's add $1 = 10^0$ to $10^{15}$ and $10^{16}$, respectively. We see that in the second case, the $1$ somehow gets lost.

In [82]:
1e15 + 1e0

1000000000000001.0

In [83]:
1e16 + 1e0

1e+16

Of course, we can also just add the integer $1$ to floats in the `e` notation and get the same result.

In [84]:
1e15 + 1

1000000000000001.0

In [85]:
1e16 + 1

1e+16

Interactions between very large and very small floats are not the only source of imprecision.

In [86]:
from math import sqrt

In [87]:
sqrt(2) ** 2

2.0000000000000004

In [88]:
0.1 + 0.2

0.30000000000000004

This can become a problem if we need to check for equality.

In [89]:
sqrt(2) ** 2 == 2

False

In [90]:
0.1 + 0.2 == 0.3

False

A popular workaround is to check if the difference of the two expressions is smaller than a pre-defined threshold sufficiently close to $0$, like $10^{-15}$.

In [91]:
threshold = 1e-15

In [92]:
(sqrt(2) ** 2) - 2 < threshold

True

In [93]:
(0.1 + 0.2) - 0.3 < threshold

True

With the help of the built-in [format()](https://docs.python.org/3/library/functions.html#format) function we can show an arbitrary number of **significant digits** (a related [format()](https://docs.python.org/3/library/stdtypes.html#str.format) method is also discussed in more detail in the next notebook on text strings).

For example, let's view a couple of floats with $50$ significant digits. This analysis reveals that almost no float is precise. After $14$ or $15$ digits "weird" things happen.

In [94]:
format(0.1, ".50f")

'0.10000000000000000555111512312578270211815834045410'

In [95]:
format(0.2, ".50f")

'0.20000000000000001110223024625156540423631668090820'

In [96]:
format(0.3, ".50f")

'0.29999999999999998889776975374843459576368331909180'

In [97]:
format(1 / 3, ".50f")

'0.33333333333333331482961625624739099293947219848633'

Observe that [format()](https://docs.python.org/3/library/functions.html#format) does not round a number in the mathematical sense. It just allows us to show a certain number of the digits stored in memory and does not change these. On the contrary, the [round()](https://docs.python.org/3/library/functions.html#round) built-in function creates a new object that is a rounded version according to the common rules from math.

For example, let's "round" `1 / 3` to five digits after the period. We see that the obtained value for `roughly_a_third` is also imprecise but different from the "exact" represenation of `1 / 3` above.

In [98]:
roughly_a_third = round(1 / 3, 5)

In [99]:
roughly_a_third

0.33333

In [100]:
format(roughly_a_third, ".50f")

'0.33333000000000001517008740847813896834850311279297'

Surprisingly, $0.125$ and $0.25$ appear to be precise and equality comparison works.

In [101]:
format(0.125, ".50f")

'0.12500000000000000000000000000000000000000000000000'

In [102]:
format(0.25, ".50f")

'0.25000000000000000000000000000000000000000000000000'

In [103]:
0.125 + 0.125 == 0.25

True

### Binary Representations

In order to understand these subtleties, we need to look at the **[binary representation of floats](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)**, i.e., review the basics of the IEEE 754 standard. On modern machines, floats are modelled in so-called "double" precision with $64$ bits that are grouped as in the picture below. The first bit determines the sign ($0$ for plus, $1$ for minus), the next $11$ bits represent an $exponent$ term, and the last $52$ bits resemble the actual significant digits, the so-called $fraction$ part. The three groups are put together like so:

$$float = (-1)^{sign} * 1.fraction * 2^{exponent-1023}$$

Observe that a $1.$ is implicitly added as the first of then $53$ digits and that both $fraction$ and $exponent$ come in base $2$ representation (i.e., they both are interpreted just as the integers above) but are inserted into the formula in their decimal notations. As $exponent$ is consequently non-negative (between $0_{10}$ and $2047_{10}$ to be exact), the $-1023$ "centers" the entire $2^{exponent-1023}$ term around $1$ and allows for the period within the $1.fraction$ part to be shifted into either direction to the same extent. Floating-point numbers received their name since the period "floats" along the significant digits. The period is formally called **[radix point](https://en.wikipedia.org/wiki/Radix_point)**.  As an aside, an $exponent$ of all $0$s or all $1$s is used to model the special values NaN or infinity.

As the standard defines the exponent part to come as a power of $2$, we now see why the decimal value $0.125$ is a precise float. It simply can be represented as a power of $2$, i.e., $0.125 = (-1)^0 * 1.0 * 2^{1020-1023} = 2^{-3} = \frac{1}{8}$. In other words, the floating-point representation of $0.125_{10}$ is $0_2$, $1111111100_2 = 1020_{10}$, and $0_2$ for the three groups, respectively (omitting leading $0$s).

<img src="static/floating_point.png" width="85%" align="center">

The important fact for Python practitioners and data scientists to understand is that mapping the infinite set of the real numbers $\mathbb{R}$ to a finite set of bits leads to the imprecisions shown above and floats are usually good approximations of real numbers only with their first $14$ to $15$ digits. If more precision is required, we need to revert to other data types such as a [Decimal](https://docs.python.org/3/library/decimal.html#decimal.Decimal) or a [Fraction](https://docs.python.org/3/library/fractions.html#fractions.Fraction) as shown in the next two sections.

This [blog post](http://fabiensanglard.net/floating_point_visually_explained/) gives another neat and visual way as to how to think of floats (it uses 32-bit floats as an example as opposed to the 64-bit here) and also explains why floats become worse approximations of the reals as their absolute values increase.

The Python [documentation](https://docs.python.org/3/tutorial/floatingpoint.html) provides another good discussion of floats and the goodness of their approximations.

If we are interested in the exact bits behind a float, we can use the [hex()](https://docs.python.org/3/library/stdtypes.html#float.hex) method that returns a string beginning with "0x1." followed by the $fraction$ (in hexadecimal notation) and ending with the $exponent$ (as an integer after subtraction of the $1023$) seperated by a "p". Also, the method [as_integer_ratio()](https://docs.python.org/3/library/stdtypes.html#float.as_integer_ratio) returns the two smallest integers whose ratio best approximates the float.

In [104]:
one_eighth = 1 / 8

In [105]:
one_eighth.hex()  # the result basically says 2 ** (-3)

'0x1.0000000000000p-3'

In [106]:
one_eighth.as_integer_ratio()

(1, 8)

In [107]:
roughly_a_third.hex()

'0x1.555475a31a4bep-2'

In [108]:
roughly_a_third.as_integer_ratio()

(3002369727582815, 9007199254740992)

$0$ is also a precise float.

In [109]:
zero = 0.0

In [110]:
zero.hex()

'0x0.0p+0'

In [111]:
zero.as_integer_ratio()

(0, 1)

As seen before, the method [is_integer()](https://docs.python.org/3/library/stdtypes.html#float.is_integer) tells us if a float can be converted into an integer object without any loss in precision.

In [112]:
roughly_a_third.is_integer()

False

In [113]:
one = roughly_a_third / roughly_a_third

one.is_integer()

True

## Decimals

The [decimal](https://docs.python.org/3/library/decimal.html) module in the Standard Library provides a [Decimal](https://docs.python.org/3/library/decimal.html#decimal.Decimal) data type that can be used to represent any number to a pre-defined level of precision (i.e., infinite or "exact" precision is also not possibe with decimals) and implements arithmetic and rounding rules just like we would expect from math. The downside is that decimals' memory allocation is not as simple and calculations are typically slower.

Let's first import the data type and also the function [getcontext()](https://docs.python.org/3/library/decimal.html#decimal.getcontext).

In [114]:
from decimal import Decimal, getcontext

[getcontext()](https://docs.python.org/3/library/decimal.html#decimal.getcontext) shows us how the [decimal](https://docs.python.org/3/library/decimal.html) module is set up to work. By default, the precision is set to $28$ significant digits (i.e., roughly twice as many as floats). We could adjust that and also configure other settings, for example, how rounding works.

In [115]:
getcontext()

Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999, Emax=999999, capitals=1, clamp=0, flags=[], traps=[InvalidOperation, DivisionByZero, Overflow])

The two simplest ways to create a decimal object is to either instantiate `Decimal()` with an integer or a text string consisting of all significant digits we would like to have. In the latter case, scientific notation is also possible.

In [116]:
Decimal(42)

Decimal('42')

In [117]:
Decimal("0.1")

Decimal('0.1')

In [118]:
Decimal("1e5")

Decimal('1E+5')

Now the imprecisions in the arithmetic and in the equality comparison from the previous section are gone.

In [119]:
Decimal("0.1") + Decimal("0.2")

Decimal('0.3')

In [120]:
Decimal("0.1") + Decimal("0.2") == Decimal("0.3")

True

Arithmetic operations of decimals with integers work as integers are inherently precise and result in new decimals.

In [121]:
42 + Decimal(42) - 42

Decimal('42')

In [122]:
10 * Decimal(42)

Decimal('420')

In [123]:
Decimal(42) / 40

Decimal('1.05')

However, mixing decimals with floats results in a `TypeError` as this would potentially introduce imprecisions into the calculations.

In [124]:
1.0 * Decimal(42)

TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'

In order to preserve the precision, decimals come with many methods bound on them resembling mathematical operations. For example, [ln()](https://docs.python.org/3/library/decimal.html#decimal.Decimal.ln) and [log10()](https://docs.python.org/3/library/decimal.html#decimal.Decimal.log10) take the logarithm while [sqrt()](https://docs.python.org/3/library/decimal.html#decimal.Decimal.sqrt) calculates the square root. In general, the functions in the [math](https://docs.python.org/3/library/math.html) module in the Standard Library should only be used with floats.

In [125]:
Decimal(100).log10()

Decimal('2')

In [126]:
Decimal(2).sqrt()

Decimal('1.414213562373095048801688724')

The [sqrt()](https://docs.python.org/3/library/decimal.html#decimal.Decimal.sqrt) method is still limited with respect to the precision of the returned value as, for example, $\sqrt{2}$ is an **[irrational number](https://en.wikipedia.org/wiki/Irrational_number)** that cannot be expressed using any type of digits even in theory.

We see this as raising $\sqrt{2}$ to the power of $2$ results in an imprecise value as before, even with decimal objects.

In [127]:
two = Decimal(2).sqrt() ** 2

two

Decimal('1.999999999999999999999999999')

The [quantize()](https://docs.python.org/3/library/decimal.html#decimal.Decimal.quantize) method allows us to cut off a decimal at any digit that is smaller than the set precision while adhering to the rounding rules from math.

For example, as the overall imprecise value of `two` still has a precision of $28$, we can correctly round it with respect to the first $20$ digits.

In [128]:
two.quantize(20)

Decimal('2')

Consequently, with this little workaround $\sqrt{2}^2 = 2$ works even in Python.

In [129]:
two.quantize(20) == 2

True

The only downside is that the entire expression is not as pretty as `sqrt(2) ** 2 == 2`.

In [130]:
(Decimal(2).sqrt() ** 2).quantize(20) == 2

True

NaN and positive and negative infinity exist as well as special values and the same remarks from above apply.

In [131]:
Decimal("NaN")

Decimal('NaN')

In [132]:
Decimal("NaN") == Decimal("NaN")  # NaN's never compare equal to anything, not even to themselves

False

In [133]:
Decimal("inf")

Decimal('Infinity')

In [134]:
Decimal("-inf")

Decimal('-Infinity')

In [135]:
Decimal("inf") + 42  # Infinity is infinity, concrete numbers loose its meaning

Decimal('Infinity')

In [136]:
Decimal("inf") + 42 == Decimal("inf")

True

As with floats, we cannot add infinities of different signs and now get a module-specific `InvalidOperation` exception instead of a `NaN` value.

In [137]:
Decimal("inf") + Decimal("-inf")

InvalidOperation: [<class 'decimal.InvalidOperation'>]

In [138]:
Decimal("inf") - Decimal("inf")

InvalidOperation: [<class 'decimal.InvalidOperation'>]

For more information on decimals, we refer to either the tutorial at [PYMOTW](https://pymotw.com/3/decimal/index.html) or the official [documentation](https://docs.python.org/3/library/decimal.html).

## Fractions

If the numbers in our application can be expressed as [rational numbers](https://en.wikipedia.org/wiki/Rational_number) $\mathbb{Q}$ in the mathematical sense, we can model them as a [Fraction](https://docs.python.org/3/library/fractions.html#fractions.Fraction) data type from the [fractions](https://docs.python.org/3/library/fractions.html) module in the Standard Library. Fractions maintain 100% of the precision as long as we do not use them in a mathematical operation that necessarily results in irrational numbers (e.g., square roots).

In [139]:
from fractions import Fraction

Among others, there are two simple ways to create a fraction object: we can either instantiate `Fraction()` with two integers representing the numerator and denominator or with a text string. In the latter case, we have again two options and can use a string either in the format "numerator/denominator" (i.e., without any spaces) or in the same format as for floats and decimals (the numerator and denominator are then computed automatically and the precision is implied implicitly; scientific notation is possible).

In [140]:
Fraction(1, 3)  # this is now 1/3 with full precision

Fraction(1, 3)

In [141]:
Fraction("1/3")  # this is 1/3 with full precision again

Fraction(1, 3)

In [142]:
Fraction("0.3333333333")  # this is 1/3 with a precision of 10 digits

Fraction(3333333333, 10000000000)

In [143]:
Fraction("3333333333e-10")  # the same in scientific notation

Fraction(3333333333, 10000000000)

Note that only the lowest common denominator version is maintained after creation, i.e., $\frac{3}{2}$ and $\frac{6}{4}$ are the same.

In [144]:
Fraction(3, 2)

Fraction(3, 2)

In [145]:
Fraction(6, 4)

Fraction(3, 2)

We could also convert a decimal object into a fraction object.

In [146]:
Fraction(Decimal("0.1"))

Fraction(1, 10)

Fractions follow the arithmetic rules from middle school and can be mixed with integers "naturally".

In [147]:
Fraction(3, 2) + Fraction(1, 4)

Fraction(7, 4)

In [148]:
Fraction(5, 2) - 2

Fraction(1, 2)

In [149]:
3 * Fraction(1, 3)

Fraction(1, 1)

In [150]:
Fraction(3, 2) * Fraction(2, 3)

Fraction(1, 1)

Fractions mix with floats syntactically. However, then the results suffer from inherent imprecision again.

In [151]:
10.0 * Fraction(1, 100)

0.1

In [152]:
format(10.0 * Fraction(1, 100), ".50f")

'0.10000000000000000555111512312578270211815834045410'

For some more examples and discussions, see the tutorial at [PYMOTW](https://pymotw.com/3/fractions/index.html) or the official [documentation](https://docs.python.org/3/library/fractions.html).

## Complex Numbers

Some mathematical equations cannot be solved if the solution has to be in the set of the real numbers $\mathbb{R}$, for example: $x^2 = -1 \implies x = \sqrt{-1}$ and the square root is not defined for negative numbers. To mitigate this, mathematicians introduced the concept of an [imaginary number](https://en.wikipedia.org/wiki/Imaginary_number) $\textbf{i}$ that is just defined as $\textbf{i} = \sqrt{-1}$ or often times as $\textbf{i}^2 = -1$. So the solution to the equation becomes $x = \textbf{i}$.

If we generalize the example equation into $(mx-n)^2 = -1 \implies x = \frac{1}{m}(\sqrt{-1} + n)$ where $m$ and $n$ are just some constants chosen from the reals $\mathbb{R}$, then the solution to the equation comes in the form $x = a + b\textbf{i}$, the sum of a real number and an imaginary number, with $a=\frac{n}{m}$ and $b = \frac{1}{m}$ also from the reals $\mathbb{R}$.

Such a "compound" number is also called a **[complex number](https://en.wikipedia.org/wiki/Complex_number)** and the set of all such numbers is commonly denoted by $\mathbb{C}$. The reals $\mathbb{R}$ are a strict subset of $\mathbb{C}$ with $b=0$. $a$ is referred to as the **real part** and $b$ as the **imaginary part** of the complex number.

Often times, complex numbers are visualized in a plane like below where the real part is depicted on the x-axis and the imaginary part is depicted on the y-axis.

<img src="static/complex_numbers.png" width="25%" align="center">

Complex numbers are part of core Python. The simplest way to create one is to write an arithmetic expression with a `j` notation for an imaginary number, which is a symbol commonly used in many engineering disciplines instead of the symbol $\textbf{i}$ from math. The reason for this is that $I$ in engineering more often than not means [electric current](https://en.wikipedia.org/wiki/Electric_current).

For example, the answer to $x^2 = -1$ can be written in Python like this. As with all values in Python, it is a full-fledged object and its type is `complex`. The same syntactic rules apply as with the above `e` in the context of scientific notation, i.e., no spaces are allowed between the number and the `j` and the number can be any float literal.

In [153]:
sqrt_of_neg_one = 1j

In [154]:
id(sqrt_of_neg_one)

140652007453040

In [155]:
type(sqrt_of_neg_one)

complex

In [156]:
sqrt_of_neg_one

1j

To verify that it solves the equation, let's just raise it to the power of $2$: the answer is $-1 + 0\textbf{i} = -1$.

In [157]:
sqrt_of_neg_one ** 2 == -1

True

Often, we will write an expression of the form $a + b\textbf{i}$.

In [158]:
2 + 0.5j

(2+0.5j)

Alternatively, we can use the [complex()](https://docs.python.org/3/library/functions.html#complex) built-in function which takes two parameters where the second is optional. We can either call it with one or two arguments of any numeric type or one text string that comes in the form of the previous code cell without any spaces.

In [159]:
complex(2, 0.5)  # an integer and a float work just fine as arguments

(2+0.5j)

In [160]:
complex(2)  # by omitting the second arguments we set the imaginary part to 0

(2+0j)

In [161]:
complex(Decimal("2.0"), Fraction(1, 2))  # the arguments can be any numeric type

(2+0.5j)

In [162]:
complex("2+0.5j")

(2+0.5j)

Spaces in the text string version lead to a `ValueError`.

In [163]:
complex("2 + 0.5j")

ValueError: complex() arg is a malformed string

The basic arithmetic rules work for complex numbers. They can naturally be mixed with other numeric types and the result is always a complex number.

In [164]:
e = 1 + 2j
f = 3 + 4j

In [165]:
e + f

(4+6j)

In [166]:
f - e

(2+2j)

In [167]:
39 + e

(40+2j)

In [168]:
3.0 - f

-4j

In [169]:
5 * e

(5+10j)

In [170]:
f / 6

(0.5+0.6666666666666666j)

In [171]:
e * f

(-5+10j)

In [172]:
f / e

(2.2-0.4j)

The absolute value of a complex number can be calculated with the Pythagoram Theorem where $\lVert x \rVert = \sqrt{a^2 + b^2}$ and the [abs()](https://docs.python.org/3/library/functions.html#abs) built-in function works correctly.

In [173]:
abs(3 + 4j)

5.0

A complex number object comes with two attributes `real` and `imag` that return the two parts as `float` types.

In [174]:
e.real

1.0

In [175]:
e.imag

2.0

Also, a conjugate() method is bound to every complex number object. The [complex conjugate](https://en.wikipedia.org/wiki/Complex_conjugate) is just the complex number with identical real part but an imaginary part equal in magnitude but opposite in sign.

In [176]:
e.conjugate()

(1-2j)

Note that the [cmath](https://docs.python.org/3/library/cmath.html) module in the Standard Library implements many of the functions from the [math](https://docs.python.org/3/library/math.html) module such that they work with complex numbers.